-- MySQL Script generated by MySQL Workbench
-- Tue Apr 17 09:43:04 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `corpus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `corpus` ;

CREATE TABLE IF NOT EXISTS `corpus` (
  `id` VARCHAR(40) NOT NULL,
  `title` VARCHAR(255) NULL,
  `user_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entity_configurations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `entity_configurations` ;

CREATE TABLE IF NOT EXISTS `entity_configurations` (
  `id` VARCHAR(40) NOT NULL,
  `color` VARCHAR(45) NULL,
  `text_color` VARCHAR(45) NULL,
  `display_name` VARCHAR(255) NULL,
  `type` VARCHAR(255) NULL,
  `corpus_id` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`, `corpus_id`),
  INDEX `fk_entity_configurations_corpus_idx` (`corpus_id` ASC),
  CONSTRAINT `fk_entity_configurations_corpus`
    FOREIGN KEY (`corpus_id`)
    REFERENCES `corpus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `models` ;

CREATE TABLE IF NOT EXISTS `models` (
  `id` VARCHAR(40) NOT NULL,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `created_on` DATETIME NULL,
  `file_location` VARCHAR(255) NULL,
  `corpus_id` VARCHAR(40) NOT NULL,
  `user_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `corpus_id`),
  INDEX `fk_models_corpus1_idx` (`corpus_id` ASC),
  CONSTRAINT `fk_models_corpus1`
    FOREIGN KEY (`corpus_id`)
    REFERENCES `corpus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
